[package]
name = "atomic_refcell_try"
version = "0.2.0"
authors = ["Bobby Holley <bobbyholley@gmail.com>"]
description = "Threadsafe RefCell"
license = "Apache-2.0/MIT"
repository = "https://github.com/jojolepro/atomic_refcell"
documentation = "https://docs.rs/atomic_refcell_try/"

[dependencies]
